name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    # At the beginning of every day (UTC).
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering
permissions:
  # To write the generated contents to the README.
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pull in leimao.github.io articles
        uses: leimao/blog-post-workflow@v1
        with:
          feed_list: "https://blog.xiang578.com/atom.xml"
          max_post_count: 8
